### PR TITLE
Add minimal support for lando

### PR DESCRIPTION
**Pull request by jedihe**
Minimal support for Lando is very easy to add and maintain. Having it also reduces barriers for new contributors.

This minimal setup allows running rector from inside the appserver container managed by Lando:

```
lando rector process web/modules/custom/rector_examples/node_load.php --dry-run
```

The path to the file autocompletes naturally from the host system, which is a small but useful convenience to have.

### CODE REVIEW

**Comment by agentrickard** [comment]
Anything dealing with Lando needs to document the version of Lando that is required.

**Comment by jedihe** [comment]
Thanks @agentrickard! is it ok to just add the version this was tested with to the quick-help embedded in .lando.yml, or should it be done in dedicated docs? (README.md, I'm guessing).

**Comment by agentrickard** [comment]
I'm torn.

The core issue I have encountered with Lando is that each version of Lando installs and requires a specific version of Docker, which can change from Lando build to build. 

- That means that all Lando projects I've used have to be pinned to a specific version of Lando/Docker.
- That means that one Lando project can break all my other Docker projects, since I use DDEV.

As a result, I avoid Lando entirely. 

Since you have Docker installed, DDEV should already work, so I don't see what adding Lando support gets us except more dependencies to manage and support.

**Comment by jedihe** [comment]
Hi @agentrickard! thanks so much for the very detailed explanation on why Lando is difficult to properly maintain.

Given that, I think it's better to close this as a won't fix 😄.

Thanks a lot for all the work you've put into Drupal Rector; as I encounter other chances to contribute, I'll try to get some time to do that.

**Pull request closed without merging**
